//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/GarammStudio/Input/InputControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace GarammStudio.Core
{
    public partial class @InputControls: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputControls"",
    ""maps"": [
        {
            ""name"": ""Adventure"",
            ""id"": ""09fef11c-d090-484c-8aa3-4290e3e4eaaf"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""07d83b96-951b-4998-a979-c32f58d00a3c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inspect"",
                    ""type"": ""Button"",
                    ""id"": ""ace63bf6-585c-4270-88e0-e5fb177da52b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ae0334d8-4279-48e9-8a62-c004d5646757"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c297245d-5a53-482b-9391-eb6e6104aff5"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Desktop"",
                    ""action"": ""Inspect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Desktop"",
            ""bindingGroup"": ""Desktop"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Adventure
            m_Adventure = asset.FindActionMap("Adventure", throwIfNotFound: true);
            m_Adventure_Move = m_Adventure.FindAction("Move", throwIfNotFound: true);
            m_Adventure_Inspect = m_Adventure.FindAction("Inspect", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Adventure
        private readonly InputActionMap m_Adventure;
        private List<IAdventureActions> m_AdventureActionsCallbackInterfaces = new List<IAdventureActions>();
        private readonly InputAction m_Adventure_Move;
        private readonly InputAction m_Adventure_Inspect;
        public struct AdventureActions
        {
            private @InputControls m_Wrapper;
            public AdventureActions(@InputControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Adventure_Move;
            public InputAction @Inspect => m_Wrapper.m_Adventure_Inspect;
            public InputActionMap Get() { return m_Wrapper.m_Adventure; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(AdventureActions set) { return set.Get(); }
            public void AddCallbacks(IAdventureActions instance)
            {
                if (instance == null || m_Wrapper.m_AdventureActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_AdventureActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Inspect.started += instance.OnInspect;
                @Inspect.performed += instance.OnInspect;
                @Inspect.canceled += instance.OnInspect;
            }

            private void UnregisterCallbacks(IAdventureActions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Inspect.started -= instance.OnInspect;
                @Inspect.performed -= instance.OnInspect;
                @Inspect.canceled -= instance.OnInspect;
            }

            public void RemoveCallbacks(IAdventureActions instance)
            {
                if (m_Wrapper.m_AdventureActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IAdventureActions instance)
            {
                foreach (var item in m_Wrapper.m_AdventureActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_AdventureActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public AdventureActions @Adventure => new AdventureActions(this);
        private int m_DesktopSchemeIndex = -1;
        public InputControlScheme DesktopScheme
        {
            get
            {
                if (m_DesktopSchemeIndex == -1) m_DesktopSchemeIndex = asset.FindControlSchemeIndex("Desktop");
                return asset.controlSchemes[m_DesktopSchemeIndex];
            }
        }
        public interface IAdventureActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnInspect(InputAction.CallbackContext context);
        }
    }
}
